# Some numpy thingies to check. 

## Permutations over columns, rows, etc.

Main take-away: 

* np.random.shuffle() performs permutation in-place
* np.random.permutation() makes a copy of the matrix



In [20]:
import numpy as np

A = np.arange(10)
A = np.tile(A, (5,1))
idx = np.arange(5)
A = np.insert(A, 0, idx, axis=1)

# After each in-place operation we copy the matrix A back to have the original matrix again
A_orig=np.copy(A)

print("Original matrix")
print(A)

print()
print("Permute over rows")
B = np.random.permutation(A)
print(B)

print()
print("Permute over rows (in-place)")
np.random.shuffle(A)
print(A)
A=np.copy(A_orig)

print()
print("Permute over columns")
B = np.random.permutation(A.T).T
print(B)

print()
print("Permute each row differently (in-place)")
for i in range(len(A)):
    np.random.shuffle(A[i])
print(A)
A=np.copy(A_orig)

Original matrix
[[0 0 1 2 3 4 5 6 7 8 9]
 [1 0 1 2 3 4 5 6 7 8 9]
 [2 0 1 2 3 4 5 6 7 8 9]
 [3 0 1 2 3 4 5 6 7 8 9]
 [4 0 1 2 3 4 5 6 7 8 9]]

Permute over rows
[[1 0 1 2 3 4 5 6 7 8 9]
 [3 0 1 2 3 4 5 6 7 8 9]
 [4 0 1 2 3 4 5 6 7 8 9]
 [0 0 1 2 3 4 5 6 7 8 9]
 [2 0 1 2 3 4 5 6 7 8 9]]

Permute over rows (in-place)
[[1 0 1 2 3 4 5 6 7 8 9]
 [4 0 1 2 3 4 5 6 7 8 9]
 [0 0 1 2 3 4 5 6 7 8 9]
 [2 0 1 2 3 4 5 6 7 8 9]
 [3 0 1 2 3 4 5 6 7 8 9]]

Permute over columns
[[8 9 3 1 5 0 4 2 6 0 7]
 [8 9 3 1 5 1 4 2 6 0 7]
 [8 9 3 1 5 2 4 2 6 0 7]
 [8 9 3 1 5 3 4 2 6 0 7]
 [8 9 3 1 5 4 4 2 6 0 7]]

Permute each row differently (in-place)
[[4 9 2 1 7 0 6 5 8 3 0]
 [3 2 6 8 1 5 0 1 9 7 4]
 [5 2 7 1 9 8 2 6 0 3 4]
 [2 5 9 3 4 3 8 7 0 1 6]
 [5 4 4 6 1 2 0 7 3 8 9]]
