In [9]:
import numpy as np

A = np.arange(10)
A = np.tile(A, (5,1))

print("Original matrix")
print(A)

#print("Permute over rows")
#B = np.random.permutation(A)
#print(B)

#print("Permute over rows in place")
#D = A.copy()
#np.random.shuffle(D)
#print(D)

print("Permute over columns")
B = np.random.permutation(A.T).T
print(B)

print("Permute each row differently")
C = A.copy()
for i in range(len(C)):
    np.random.shuffle(C[i])
print(C)

print("Permute each row in line")
for i in range(len(A)):
    np.random.shuffle(A[i])
print(A)

Original matrix
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
Permute over columns
[[4 7 1 5 6 8 0 3 9 2]
 [4 7 1 5 6 8 0 3 9 2]
 [4 7 1 5 6 8 0 3 9 2]
 [4 7 1 5 6 8 0 3 9 2]
 [4 7 1 5 6 8 0 3 9 2]]
Permute each row differently
[[3 4 1 2 6 0 8 5 9 7]
 [0 5 2 1 8 6 4 3 7 9]
 [6 0 1 9 8 5 7 3 2 4]
 [7 5 9 8 2 6 4 0 3 1]
 [1 0 4 7 2 3 5 8 6 9]]
Permute each row in line
[[9 0 8 6 5 1 3 7 4 2]
 [2 7 5 1 9 6 8 4 0 3]
 [8 5 4 3 7 0 2 9 1 6]
 [8 2 4 9 3 5 0 6 7 1]
 [1 8 9 7 4 3 0 6 2 5]]
